CREATE SEQUENCE SEQ_TESTIMONIAL;

CREATE TABLE TBL_TESTIMONIAL(
	TESTIMONIAL_ID NUMBER CONSTRAINT PK_TESTIMONIAL PRIMARY KEY,
	TESTIMONIAL_TITLE VARCHAR2(500) NOT NULL,
	TESTIMONIAL_CONTENT VARCHAR2(1000) NOT NULL,
	TESTIMONIAL_REGISTER_DATE DATE DEFAULT SYSDATE,
	TESTIMONIAL_UPDATE_DATE DATE DEFAULT SYSDATE,
	TESTIMONIAL_USER_ID NUMBER,
	CONSTRAINT FK_USER_ID FOREIGN KEY (TESTIMONIAL_USER_ID) REFERENCES TBL_USER (USER_ID)
);


CREATE SEQUENCE SEQ_USER;

CREATE TABLE TBL_USER(
	USER_NO NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_ID VARCHAR2(1000) CONSTRAINT UK_USER_ID UNIQUE NOT NULL,
	USER_PW VARCHAR2(1000) NOT NULL,
	USER_NAME VARCHAR2(1000) NOT NULL,
	USER_PHONENUMBER VARCHAR2(1000) NOT NULL,	
	USER_AGE NUMBER(3) NOT NULL,
	USER_GENDER VARCHAR2(1000) NOT NULL,
	USER_EMAIL VARCHAR2(500),
	USER_ZIPCODE VARCHAR2(500),
	USER_ADDRESS VARCHAR2(1000),
	USER_ADDRESS_DETAIL VARCHAR2(1000),
	USER_ADDRESS_ETC VARCHAR2(1000)
);

SELECT * FROM TBL_USER;


CREATE SEQUENCE SEQ_PRODUCT;


CREATE TABLE TBL_PRODUCT(
	PRODUCT_ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(500) NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 0,
	PRODUCT_PRICE NUMBER DEFAULT 0
);


CREATE SELECT SEQ_NEWS;


CREATE TABLE TBL_NEWS(
	NEWS_ID NUMBER CONSTRAINT PK_NEWS PRIMARY KEY,
	NEWS_TITLE VARCHAR2(500) NOT NULL,
	NEWS_WRITER VARCHAR2(500) NOT NULL,
	NEWS_CONTENT VARCHAR2(500) NOT NULL,
	NEWS_REGISTER_DATE DEFAULT SYSDATE,
	NEWS_UPDATE_DATE DEFAULT SYSDATE
);